# Generated by Django 5.1 on 2025-02-04 14:46

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='insight',
            options={'ordering': ['-date_posted'], 'verbose_name': 'Financial Insight', 'verbose_name_plural': 'Financial Insights'},
        ),
        migrations.AddField(
            model_name='insight',
            name='is_automated',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='insight',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='insights', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='insight',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
